language: php

php:
  - 7.0

sudo: false

git:
  depth: 3

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install --dev --no-interaction --no-progress --prefer-dist
  - mkdir -p build/phpunit
  - wget http://get.sensiolabs.org/php-cs-fixer.phar -O php-cs-fixer
  - chmod a+x php-cs-fixer

script:
  - phpunit
  - php php-cs-fixer fix --dry-run --verbose --diff

after_success:
  - composer require --dev satooshi/php-coveralls
  - travis_retry php vendor/bin/coveralls -v
