language: php

php:
  - 7.0

sudo: false

git:
  depth: 3

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install --dev --no-interaction --no-progress --prefer-dist

script:
  - mkdir -p build/phpunit
  - phpunit

after_success:
  - composer require --dev satooshi/php-coveralls
  - travis_retry php vendor/bin/coveralls -v
